#.travis.yml
sudo: required
dist: trusty
language: node_js
node_js:
  - '12'
before_install:
  - rm -rf node_modules
  - yarn global add ganache-cli
install:
  - yarn install
before_script:
  - ganache-cli --defaultBalanceEther 500000000 > /dev/null &
  - sleep 5
script:
  - cd $TRAVIS_BUILD_DIR/travscripts
  - "chmod +x ./BranchScript.sh && ./BranchScript.sh"
